import './globals.css'
import Navbar from "@/components/ui/navbar"
import type { Metadata } from 'next'
import { Lato } from 'next/font/google'

const lato = Lato({ weight: '700', subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
